all: build_select_server

# 3_2
build_select_server:
	g++ practice_3_2_select_server.cpp -ggdb -o0 -o select_server

# 3_1
# build_server:
# 	g++ -ggdb -o0 -o server practice_3_1_tcp_server.cpp

# build_client:
# 	g++ -ggdb -o0 -o client practice_3_1_tcp_client.cpp
